import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Outfit,
  Bebas_Neue,
  Shadows_Into_Light,
} from "next/font/google";

import Navbar from "../components/layout/Navbar";
import Footer from "../components/layout/Footer";
import "./globals.css";
import SmoothScroll from "@/components/ui/SmothScroll";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  weight: "400",
  subsets: ["latin"],
});

const shadowsIntoLight = Shadows_Into_Light({
  variable: "--font-shadow-light",
  weight: "400",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Spotlight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${outfit.variable}
          ${bebasNeue.variable}
          ${shadowsIntoLight.variable}
          antialiased
        `}
      >
        <div className="min-h-screen flex flex-col">
          <Navbar />
          <SmoothScroll>
            <main className="flex-1">{children}</main>
          </SmoothScroll>
          <Footer />
        </div>
      </body>
    </html>
  );
}
